# Generated by Django 4.1.3 on 2022-12-18 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_braintreecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BraintreeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.appointment')),
            ],
        ),
    ]
