# Generated by Django 4.1.3 on 2023-01-02 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_braintreetransaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='braintreetransaction',
            name='amount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='braintreetransaction',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='braintreetransaction',
            name='source',
            field=models.IntegerField(choices=[(1, 'Session'), (2, 'Donation')], default=1),
        ),
    ]
