# Generated by Django 4.1.3 on 2022-12-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_braintreetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='braintreetransaction',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='console.appointment'),
        ),
        migrations.AlterField(
            model_name='braintreetransaction',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
