# Generated by Django 4.1.3 on 2022-11-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='display_photo',
            new_name='image',
        ),
    ]
