# Generated by Django 4.1.3 on 2023-01-21 13:59

from django.db import migrations, models
import django.utils.timezone
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.FileField(blank=True, upload_to=website.models.package_directory_path)),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.FileField(blank=True, upload_to=website.models.package_directory_path),
        ),
    ]
