# Generated by Django 4.1.3 on 2023-07-26 01:08

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_news_content_news_slug_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.IntegerField(choices=[(1, 'Short'), (2, 'Long')], default=1, verbose_name='Package Type'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=website.models.blog_directory_path),
        ),
    ]
