# Generated by Django 4.1.3 on 2023-07-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_package_package_type_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
