# Generated by Django 4.1.3 on 2022-12-01 12:13

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_photo',
            field=models.FileField(blank=True, upload_to=auth_app.models.user_directory_path),
        ),
    ]
