# Generated by Django 4.1.3 on 2022-12-20 09:22

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_photo',
            field=models.FileField(blank=True, null=True, upload_to=auth_app.models.user_directory_path),
        ),
    ]
